server:
  port: 8086
spring:
  application:
    name: notification-service
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:25}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
topics:
  planCreated: meds.plan.created
