server:
  port: 8085
spring:
  application:
    name: translation-service
  security:
    user: # disable auth by permitting all via filter
      name: dummy
      password: dummy
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka